# -*- coding: utf-8 -*-
"""Annotazione_Manuale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zFwG2GM9TgOqQiWeMQandGUen_i-4wS

# Drive / Google / installazioni
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import auth
auth.authenticate_user()
import gspread
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)

!pip install cellpose torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118

!pip install scikit-image scikit-learn pandas seaborn matplotlib opencv-python-headless

!pip install gspread-dataframe

"""# Configurazione"""

# ================================================================
# CONFIGURATION: paths and model initialization
# ================================================================

import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from skimage.morphology import remove_small_objects
from skimage.measure import label, regionprops
from skimage.feature import peak_local_max
from skimage.segmentation import watershed
from scipy import ndimage as ndi

from cellpose import models

# Base dataset folder on Google Drive (EDIT if needed)
BASE_DATASET_DIR = "/content/drive/MyDrive/Prova_user_manual"

# Example image path to annotate (EDIT and change the category)
TEST_IMAGE_PATH = os.path.join(
    BASE_DATASET_DIR,
    "Exhausted",
    "T-Velia_6D__2S_-_00177.tif",
)

# Initialize Cellpose-SAM model once (GPU=True if available)
cp_model = models.CellposeModel(gpu=True, pretrained_model="cpsam")

"""# Funzione di segmentazione ed estrazione feature"""

# ================================================================
# FUNCTION: segment a brightfield image with Cellpose-SAM
# ================================================================

def segment_image_cpsam(img_path):
    """
    Segment a brightfield T-cell image using Cellpose-SAM, followed by
    basic morphological cleanup and watershed splitting of large blobs.

    Parameters
    ----------
    img_path : str
        Full path to the input image (grayscale brightfield).

    Returns
    -------
    img_gray : np.ndarray (H, W), uint8
        Original grayscale image.
    masks_cp : np.ndarray (H, W), int32
        Label image of segmented cells: 0 = background, 1..N = cell labels.
    img_eq : np.ndarray (H, W), uint8
        Preprocessed equalized image used for feature extraction.

    Steps
    -----
    1. Load image in grayscale.
    2. Remove smooth background (unsharp mask) to enhance edges.
    3. Apply local contrast enhancement (CLAHE).
    4. Normalize image to 0–1 and run Cellpose-SAM.
    5. Remove small objects and smooth edges.
    6. Use watershed on distance map to split large blobs into separate cells.
    """
    # 1) Load grayscale image
    img_gray = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img_gray is None:
        raise FileNotFoundError(f"Image not found or unreadable: {img_path}")

    # 2) Background removal (unsharp mask)
    img_f = img_gray.astype(np.float32)
    blur = cv2.GaussianBlur(img_f, (0, 0), 4)
    img_bg_removed = cv2.addWeighted(img_f, 1.9, -blur, 0.5, 0)

    # 3) Local contrast enhancement (CLAHE)
    img_bg_removed = np.clip(img_bg_removed, 0, 255).astype(np.uint8)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    img_eq = clahe.apply(img_bg_removed)

    # 4) Normalize to 0–1 for Cellpose
    img_norm = img_eq.astype(np.float32)
    img_norm = (img_norm - img_norm.min()) / (img_norm.max() - img_norm.min() + 1e-8)

    # 5) Cellpose-SAM segmentation (single-channel image)
    masks_cp, flows, styles = cp_model.eval(
        img_norm,
        channels=[0, 0],  # [cytoplasm, nucleus]; here both are same gray channel
    )

    # 6) Morphological cleanup: remove small objects and smooth boundaries
    masks_cp = remove_small_objects(masks_cp.astype(bool), min_size=3000)

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    masks_cp = cv2.morphologyEx(
        masks_cp.astype(np.uint8),
        cv2.MORPH_OPEN,
        kernel,
    )

    # 7) Watershed: split large blobs (touching cells)
    lab0 = label(masks_cp.astype(bool))
    lab_final = np.zeros_like(lab0, dtype=np.int32)
    current_label = 1

    for r in regionprops(lab0):
        # mask of a single connected component (blob)
        blob_mask = (lab0 == r.label)

        # If the blob is not too large, keep it as a single cell
        if r.area < 18000:  # threshold to tune if needed
            lab_final[blob_mask] = current_label
            current_label += 1
            continue

        # For large blobs, compute distance transform
        distance = ndi.distance_transform_edt(blob_mask)

        # Find local maxima as candidate cell centers
        coords = peak_local_max(
            distance,
            footprint=np.ones((50, 50)),  # minimum distance between centers
            labels=blob_mask,
        )

        # Prepare markers for watershed
        local_max = np.zeros_like(distance, dtype=bool)
        if coords.size > 0:
            local_max[coords[:, 0], coords[:, 1]] = True

        markers = ndi.label(local_max)[0]
        ws = watershed(-distance, markers, mask=blob_mask)

        # Assign new labels to each watershed region
        for k in np.unique(ws)[1:]:  # skip background label 0
            lab_final[ws == k] = current_label
            current_label += 1

    masks_cp = lab_final  # final labeled mask

    return img_gray, masks_cp, img_eq

# ================================================================
# FUNCTION: extract geometric and intensity features for each cell
# ================================================================

def parameters(img_gray, masks_cp, img_eq, bg_ring=3):
    """
    Compute geometric and intensity-based features for each segmented cell.

    Parameters
    ----------
    img_gray : np.ndarray (H, W), uint8
        Original grayscale image.
    masks_cp : np.ndarray (H, W), int32
        Labeled mask of cells (output of segment_image_cpsam).
    img_eq : np.ndarray (H, W), uint8
        Equalized image used for intensity measurements.
    bg_ring : int, optional
        Thickness (in pixels) of the ring around the cell used to estimate
        local background statistics.

    Returns
    -------
    df_cells : pandas.DataFrame
        One row per cell with:
        - label, area, perimeter, circularity, solidity, eccentricity,
          major_axis, minor_axis, aspect_ratio, extent
        - mean_int, max_int, min_int, std_int, median_int
        - bg_mean, bg_median, contrast_mean, contrast_max, ratio_mean,
          edge_int_mean
        - visibility, quality_score
    """
    lab = label(masks_cp)
    regions = regionprops(lab, intensity_image=img_eq)

    cells = []

    for r in regions:
        # --- basic shape ---
        area = r.area
        perimeter = r.perimeter

        circularity = 4 * np.pi * area / (perimeter**2 + 1e-8)
        solidity = r.solidity
        eccentricity = getattr(r, "eccentricity", np.nan)
        major_axis = getattr(r, "major_axis_length", np.nan)
        minor_axis = getattr(r, "minor_axis_length", np.nan)

        if minor_axis == 0:
            aspect_ratio = np.nan
        else:
            aspect_ratio = major_axis / minor_axis

        # extent = area / area of bounding box
        minr, minc, maxr, maxc = r.bbox
        bbox_area = (maxr - minr) * (maxc - minc)
        extent = area / (bbox_area + 1e-8)

        # --- intensity inside the cell (using equalized image) ---
        mean_int = r.mean_intensity
        max_int = getattr(r, "max_intensity", np.nan)
        min_int = getattr(r, "min_intensity", np.nan)

        intens_vals = img_eq[r.slice][r.image]  # pixels of this cell
        std_int = float(np.std(intens_vals))
        median_int = float(np.median(intens_vals))

        # --- local background ring around the cell ---
        cell_mask = np.zeros_like(masks_cp, dtype=np.uint8)
        cell_mask[lab == r.label] = 1

        kernel_size = 2 * bg_ring + 1
        kernel = cv2.getStructuringElement(
            cv2.MORPH_ELLIPSE,
            (kernel_size, kernel_size),
        )

        dilated = cv2.dilate(cell_mask, kernel, iterations=1)
        ring = (dilated == 1) & (cell_mask == 0)

        ring_vals = img_eq[ring]
        if ring_vals.size > 0:
            bg_mean = float(np.mean(ring_vals))
            bg_median = float(np.median(ring_vals))
        else:
            bg_mean = np.nan
            bg_median = np.nan

        # --- derived intensity/contrast features ---
        contrast_mean = mean_int - bg_mean if not np.isnan(bg_mean) else np.nan
        contrast_max = max_int - bg_mean if not np.isnan(bg_mean) else np.nan
        ratio_mean = mean_int / (bg_mean + 1e-8) if not np.isnan(bg_mean) else np.nan

        # edge intensity (mean intensity in the ring)
        if ring_vals.size > 0:
            edge_int_mean = float(np.mean(ring_vals))
        else:
            edge_int_mean = bg_mean

        # --- combined “visibility” and “quality” scores ---
        visibility = contrast_mean * solidity if not np.isnan(contrast_mean) else np.nan
        quality_score = (
            1.0 * (contrast_mean if not np.isnan(contrast_mean) else 0.0)
            + 0.5 * (circularity if not np.isnan(circularity) else 0.0) * 100
            + 0.5 * (solidity if not np.isnan(solidity) else 0.0) * 100
        )

        cells.append({
            "label": r.label,
            # shape
            "area": area,
            "perimeter": perimeter,
            "circularity": circularity,
            "solidity": solidity,
            "eccentricity": eccentricity,
            "major_axis": major_axis,
            "minor_axis": minor_axis,
            "aspect_ratio": aspect_ratio,
            "extent": extent,
            # intensity
            "mean_int": mean_int,
            "max_int": max_int,
            "min_int": min_int,
            "std_int": std_int,
            "median_int": median_int,
            # background / contrast
            "bg_mean": bg_mean,
            "bg_median": bg_median,
            "contrast_mean": contrast_mean,
            "contrast_max": contrast_max,
            "ratio_mean": ratio_mean,
            "edge_int_mean": edge_int_mean,
            # combined scores
            "visibility": visibility,
            "quality_score": quality_score,
        })

    df_cells = pd.DataFrame(cells)
    return df_cells

"""#Test"""

# Percorso immagine di test
test_path = "/content/drive/MyDrive/T-CELLS_DATASET/Exhausted/T-Velia_6D__2S_-_00177.tif"

# 1) segmenta l'immagine (usa la funzione già definita nel notebook)
img_gray, masks_cp, img_eq = segment_image_cpsam(test_path)

print("Pixel > 0 in masks_cp:", (masks_cp > 0).sum())

# 2) etichetta le cellule
lab = label(masks_cp)

# 3) calcola il DataFrame di feature
df = parameters(img_gray, masks_cp, img_eq)
print("df shape:", df.shape)
print("colonne:", df.columns.tolist())

df = df.sort_values(by="circularity", ascending=False).reset_index(drop=True)
print("Numero cellule cpsam:", len(regionprops(lab)))

# 4) visualizzazioni
if len(regionprops(lab)) == 0:
    print("Nessuna cellula trovata per questa immagine.")
else:
    # 1) bounding box sulle cellule etichettate
    img_rgb = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2BGR)

    for r in regionprops(lab):
        minr, minc, maxr, maxc = r.bbox
        cell_ID = r.label

        cv2.rectangle(
            img_rgb,
            (minc, minr),
            (maxc, maxr),
            (0, 255, 0),
            4
        )

        # testo con l'ID della cellula
        cv2.putText(
            img_rgb,
            str(cell_ID),
            (minc, max(minr - 10, 0)),
            cv2.FONT_HERSHEY_SIMPLEX,
            2,
            (255, 0, 255),
            10,
            cv2.LINE_AA
        )

    plt.figure(figsize=(6, 6))
    plt.imshow(cv2.cvtColor(img_rgb, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.title("Bounding box sulle cellule etichettate")
    plt.show()

    # 2) maschera cpsam su sfondo nero
    mask_intensity = img_eq.copy()
    mask_intensity[lab == 0] = 0  # sfondo nero

    plt.figure(figsize=(6, 6))
    plt.imshow(mask_intensity, cmap="gray")
    plt.axis("off")
    plt.title("Maschere")
    plt.show()

    # 3) immagine originale
    plt.figure(figsize=(6, 6))
    plt.imshow(img_gray, cmap="gray")
    plt.axis("off")
    plt.title("Immagine originale")
    plt.show()

    # 4) immagine equalizzata
    plt.figure(figsize=(6, 6))
    plt.imshow(img_eq, cmap="gray")
    plt.axis("off")
    plt.title("Immagine equalizzata")
    plt.show()

category = "Exhausted"

# inizializza colonna di annotazione
df["manual_label"] = "unknown"

# good / bad come da tua scelta
df.loc[df["label"].isin([5, 16, 18, 21, 22, 2]), "manual_label"] = "good"
df.loc[df["label"].isin([]), "manual_label"] = "bad"

# tieni solo le cellule annotate
df_manual = df[df["manual_label"] != "unknown"].copy()

# aggiungi metadati
df_manual["Percorso"] = test_path      # percorso o nome file
df_manual["category"] = category

# per coerenza con il resto
lab = label(masks_cp)

display(df_manual)

# Etichettatura della maschera corrente
lab = label(masks_cp)

# Cartella base per annotazioni
base_dir = "/content/drive/MyDrive/Prova_user_manual/annotazioni_manuali_exhausted"
os.makedirs(base_dir, exist_ok=True)

# Cartelle per i crop good/bad
crop_root = os.path.join(base_dir, "crops")
good_dir = os.path.join(crop_root, "good")
bad_dir = os.path.join(crop_root, "bad")
os.makedirs(good_dir, exist_ok=True)
os.makedirs(bad_dir, exist_ok=True)

crop_paths = []

for _, row in df_manual.iterrows():
    cell_id = int(row["label"])
    status = row["manual_label"]  # "good" o "bad"

    # trova la regione corrispondente al label
    r = [reg for reg in regionprops(lab) if reg.label == cell_id][0]
    minr, minc, maxr, maxc = r.bbox
    crop = img_gray[minr:maxr, minc:maxc]

    # sceglie la sottocartella in base allo status
    if status == "good":
        subdir = good_dir
    else:
        subdir = bad_dir

    # nome file: categoria_nomeimg_idXX.tif
    base_name = os.path.splitext(os.path.basename(test_path))[0]
    fname = f"{row['category']}_{base_name}_id{cell_id}.tif"
    fpath = os.path.join(subdir, fname)

    cv2.imwrite(fpath, crop)
    crop_paths.append(fpath)

# aggiungi il path dei crop al dataframe
df_manual["crop_path"] = crop_paths

# aggiorna CSV cumulativo
csv_path = os.path.join(base_dir, "annotazioni_manuali_exhausted.csv")

if os.path.exists(csv_path):
    df_old = pd.read_csv(csv_path)
    df_all_manual = pd.concat([df_old, df_manual], ignore_index=True)
else:
    df_all_manual = df_manual.copy()

df_all_manual.to_csv(csv_path, index=False)
print("Annotazioni aggiornate in:", csv_path)