# Copyright (c) 2026 Giovanni Ruocco
# Licensed under the Non-Commercial License (NCL)
# See LICENSE file for details

# -*- coding: utf-8 -*-
"""User_manual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBrobtsjmPJcP5e1RXsXqYWta0QcCmym
"""

"""
======================================================================
T-CELLS PIPELINE - BRIGHTFIELD SEGMENTATION AND CLASSIFICATION
======================================================================

This script implements an end-to-end pipeline for:

1. Loading images of T-cells (Naive / Activated / Exhausted).
2. Segmenting cells using Cellpose-SAM + morphological post-processing.
3. Extracting morphological and intensity-based features for each cell.
4. Training "good vs bad" quality models (Logistic Regression + Random Forest).
5. Training category models (Naive / Activated / Exhausted) on good cells only.
6. Applying the trained models to new images and saving results to Excel.

INTENDED USER
-------------
- Users with basic Python/Colab knowledge.
- No need to understand every ML detail: comments explain the key ideas.
- The user mainly needs to adjust input/output folders on Google Drive.

HOW TO USE
----------
1. Open this script in Google Colab (upload as .ipynb or run via %run).
2. Adjust the HARD-CODED PATHS in the "USER CONFIGURATION" section.
3. Run the script: it will:
   - Mount Google Drive.
   - Install required packages (Cellpose, scikit-learn, etc.).
   - Segment images, build feature tables, train models, and save results.

NOTE
----
- Paths are hard-coded for clarity, but clearly commented so you can change
  them to match your own Drive structure.
"""

# ======================================================================
# 1. GOOGLE COLAB SETUP AND PACKAGE INSTALLATION
# ======================================================================

# If you run this script in Google Colab, these lines mount your Drive
# and install all required libraries.
# If you run locally, you may comment/remove these and install packages
# with pip/conda on your machine.

from google.colab import drive
drive.mount('/content/drive')  # Allows access to files in your Google Drive

from google.colab import auth
auth.authenticate_user()       # For Google Sheets access (if needed)

import gspread
from google.auth import default

creds, _ = default()
gc = gspread.authorize(creds)  # Google Sheets client (not strictly required for core pipeline)

# Install scientific and ML packages.
# NOTE: The "!" syntax is specific to notebooks (Colab/Jupyter).
# If you convert to pure .py, install these manually via pip.
!pip install cellpose torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
!pip install scikit-image scikit-learn pandas seaborn matplotlib opencv-python-headless
!pip install gspread-dataframe

# ======================================================================
# 2. IMPORTS
# ======================================================================

from cellpose import models
import matplotlib.pyplot as plt
from IPython.display import display

from skimage.morphology import remove_small_objects
from skimage.measure import label, regionprops
from skimage.feature import peak_local_max
from skimage.segmentation import watershed
from scipy import ndimage as ndi

import numpy as np
import glob
import cv2
import pandas as pd
import os
import shutil

from sklearn.model_selection import train_test_split, learning_curve
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

import joblib

# ======================================================================
# 3. USER CONFIGURATION - HARD-CODED PATHS (EDIT THESE)
# ======================================================================

"""
In this section you define where your data lives in Google Drive and
where the script will save results.

If you copy this project to a different Drive folder, update these paths.
"""

# Base folder for the main T-cells dataset (3 categories: Naive, Activated, Exhausted)
BASE_DATASET_DIR = "/content/drive/MyDrive/name_folder"  # <--- EDIT if needed

# Folder containing images used only to compute mean and std for normalization
TRAINING_FOR_NORM_DIR = os.path.join(BASE_DATASET_DIR, "training_per_normalization")  # This should contain a good subset of your images

# Subfolders with images per category (inside BASE_DATASET_DIR)
CATEGORIES = ["Naive", "Activated", "Exhausted"]                                      # insert the subfolder's name (if there are)

# Folder where statistics and model outputs are saved
STATS_DIR = os.path.join(BASE_DATASET_DIR, "folder_per_statistics")

# Folder containing manual annotations (CSV/XLSX files)
MANUAL_ANNOT_DIR = os.path.join(BASE_DATASET_DIR, "Annotazioni_manuali")

# Example folders for NEW images to classify (you can change these)
NEW_IMAGES_DIR_1 = "/content/drive/MyDrive/test_folder/subfolder_1"  # <--- EDIT or add more
NEW_IMAGES_DIR_2 = "/content/drive/MyDrive/test_folder/subfolder_2"      # <--- EDIT or add more

# Make sure the statistics directory exists
os.makedirs(STATS_DIR, exist_ok=True)

# ======================================================================
# 4. INITIALIZE Cellpose-SAM MODEL
# ======================================================================

"""
We create a global Cellpose model instance that will be reused for all
segmentations. This avoids re-loading the model for each image, which
would be slow.
"""

cp_model = models.CellposeModel(gpu=True, pretrained_model="cpsam")

# ======================================================================
# 5. COMPUTE DATASET-WIDE MEAN AND STD FOR NORMALIZATION
# ======================================================================

def compute_dataset_mean_std(training_image_paths):
    """
    Compute mean and standard deviation of pixel intensities over a set of
    brightfield images, after basic preprocessing (background removal and
    local contrast enhancement).

    Parameters
    ----------
    training_image_paths : list of str
        List of full paths to images used only for estimating normalization.

    Returns
    -------
    mu : float
        Global mean of preprocessed pixel intensities.
    sigma : float
        Global standard deviation of preprocessed pixel intensities.

    Rationale
    ---------
    We want Cellpose-SAM to see images that are normalized in a consistent
    way across the dataset. We therefore:
    - convert to grayscale,
    - remove smooth background with an "unsharp mask" style filter,
    - apply CLAHE (local contrast enhancement),
    then we compute mean and std over all processed pixels.
    """
    pixels = []  # will store flattened pixel arrays from each processed image

    for img_path in training_image_paths:
        # 1) Load image in grayscale
        img_gray = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img_gray is None:

            continue

        # 2) Background removal (unsharp mask)
        img_f = img_gray.astype(np.float32)
        blur = cv2.GaussianBlur(img_f, (0, 0), 4)
        img_bg_removed = cv2.addWeighted(img_f, 1.9, -blur, 0.5, 0)             # You can adjust these values if needed

        # Clip to valid 8-bit range and convert back to uint8
        img_bg_removed = np.clip(img_bg_removed, 0, 255).astype(np.uint8)

        # 3) Local contrast enhancement (CLAHE)
        clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
        img_eq = clahe.apply(img_bg_removed)

        # 4) Store all pixels from this processed image
        pixels.append(img_eq.flatten())

    if len(pixels) == 0:
        raise RuntimeError("No valid images found in training_path for mean/std computation.")

    # 5) Concatenate all pixels and compute statistics
    all_pixels = np.concatenate(pixels)
    mu = float(np.mean(all_pixels))
    sigma = float(np.std(all_pixels))

    print(f"[Normalization] Dataset mean: {mu:.2f}")
    print(f"[Normalization] Dataset std:  {sigma:.2f}")

    return mu, sigma


# Build list of images used to estimate normalization
training_image_paths = glob.glob(os.path.join(TRAINING_FOR_NORM_DIR, "*.tif"))

# Compute mean and std on the training subset
mu, sigma = compute_dataset_mean_std(training_image_paths)

# Optionally, override with fixed values (for reproducibility)
# You can comment these lines if you always want to recompute mu, sigma.
# Those are example values
mu = 146.65
sigma = 29.66
print(f"[Normalization] Using fixed mu={mu:.2f}, sigma={sigma:.2f}")

# ======================================================================
# 6. IMAGE SEGMENTATION FUNCTION (CELLPose-SAM + WATERSHED)
# ======================================================================

def segment_image_cpsam(img_path, mu, sigma):
    """
    Segment a brightfield T-cell image using Cellpose-SAM followed by
    morphological cleanup and watershed splitting of large blobs.

    Parameters
    ----------
    img_path : str
        Full path to the input image (brightfield, single channel).
    mu : float
        Mean used for intensity normalization.
    sigma : float
        Std used for intensity normalization.

    Returns
    -------
    img_gray : np.ndarray (H, W), uint8
        Original grayscale image.
    masks_cp : np.ndarray (H, W), int32
        Label image of segmented cells: 0 = background, 1..N = cell labels.
    img_eq : np.ndarray (H, W), uint8
        Preprocessed and equalized image used for feature extraction.

    Processing steps
    ----------------
    1. Load image in grayscale.
    2. Remove smooth background (unsharp mask) to enhance cell edges.
    3. Apply CLAHE for local contrast enhancement.
    4. Normalize intensities using (pixel - mu) / sigma.
    5. Run Cellpose-SAM on the normalized image.
    6. Remove very small objects and smooth edges via morphological opening.
    7. For large connected components, apply watershed on distance map
       to split touching cells into separate labels.
    """
    # 1) Load grayscale image
    img_gray = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img_gray is None:
        raise FileNotFoundError(f"Image not found or unreadable: {img_path}")

    # 2) Background removal (unsharp mask)
    img_f = img_gray.astype(np.float32)
    blur = cv2.GaussianBlur(img_f, (0, 0), 4)
    img_bg_removed = cv2.addWeighted(img_f, 1.9, -blur, 0.5, 0)

    # 3) Local contrast enhancement (CLAHE)
    img_bg_removed = np.clip(img_bg_removed, 0, 255).astype(np.uint8)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    img_eq = clahe.apply(img_bg_removed)

    # 4) Normalization using dataset mean and std
    img_norm = (img_eq.astype(np.float32) - mu) / (sigma + 1e-8)

    # 5) Cellpose-SAM segmentation (monochannel image -> channels=[0,0])
    masks_cp, flows, styles = cp_model.eval(
        img_norm,
        channels=[0, 0]
    )

    # 6) Morphological cleanup:
    #    - remove small objects (noise)
    #    - smooth edges using morphological opening
    masks_cp = remove_small_objects(masks_cp.astype(bool), min_size=3000)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    masks_cp = cv2.morphologyEx(
        masks_cp.astype(np.uint8),
        cv2.MORPH_OPEN,
        kernel
    )

    # 7) Watershed-based splitting of large blobs to separate touching cells
    lab0 = label(masks_cp.astype(bool))  # initial labels of connected components
    lab_final = np.zeros_like(lab0, dtype=np.int32)
    current_label = 1

    for r in regionprops(lab0):
        # mask of the current connected component (blob)
        blob_mask = (lab0 == r.label)

        # If the blob is not too large, keep it as a single cell
        if r.area < 18000:  # threshold may need tuning for your images
            lab_final[blob_mask] = current_label
            current_label += 1
            continue

        # For large blobs, compute distance transform
        distance = ndi.distance_transform_edt(blob_mask)

        # Find local maxima as potential cell centers
        coords = peak_local_max(
            distance,
            footprint=np.ones((50, 50)),  # minimum separation between centers
            labels=blob_mask
        )

        # Build marker image for watershed
        local_max = np.zeros_like(distance, dtype=bool)
        if coords.size > 0:
            local_max[coords[:, 0], coords[:, 1]] = True
        markers = ndi.label(local_max)[0]

        # Apply watershed to split the blob into multiple labels
        ws = watershed(-distance, markers, mask=blob_mask)

        # Assign new labels to each watershed region
        for k in np.unique(ws)[1:]:  # skip background 0
            lab_final[ws == k] = current_label
            current_label += 1

    masks_cp = lab_final  # final labeled mask

    return img_gray, masks_cp, img_eq

# ======================================================================
# 7. FEATURE EXTRACTION FOR EACH CELL
# ======================================================================

def extract_cell_features(img_gray, masks_cp, img_eq, bg_ring=3):
    """
    Extract morphological and intensity-based features for each segmented cell.

    Parameters
    ----------
    img_gray : np.ndarray (H, W), uint8
        Original grayscale image.
    masks_cp : np.ndarray (H, W), int32
        Labeled mask of cells (output of segment_image_cpsam).
    img_eq : np.ndarray (H, W), uint8
        Equalized image used for intensity measurements.
    bg_ring : int, optional
        Radius (in pixels) of the ring around each cell used to estimate
        local background statistics.

    Returns
    -------
    df : pandas.DataFrame
        One row per cell, with the following columns:
        - label: integer label of the cell.
        - area, perimeter, circularity, solidity, eccentricity, major_axis,
          minor_axis, aspect_ratio, extent
        - mean_int, max_int, min_int, std_int, median_int
        - bg_mean, bg_median, contrast_mean, contrast_max, ratio_mean,
          edge_int_mean
        - visibility, quality_score

    Notes
    -----
    - Intensity features are computed on img_eq (preprocessed image).
    - Local background is measured in a dilated ring around the cell.
    - "quality_score" is a heuristic score combining contrast and shape
      features to assess how well-defined the cell is.
    """
    lab = label(masks_cp)
    regions = regionprops(lab, intensity_image=img_eq)

    cells = []

    for r in regions:
        # Basic shape features
        area = r.area
        perimeter = r.perimeter

        circularity = (4 * np.pi * area) / (perimeter**2 + 1e-8)
        solidity = r.solidity
        eccentricity = getattr(r, "eccentricity", np.nan)
        major_axis = getattr(r, "major_axis_length", np.nan)
        minor_axis = getattr(r, "minor_axis_length", np.nan)
        if minor_axis == 0:
            aspect_ratio = np.nan
        else:
            aspect_ratio = major_axis / minor_axis

        # Extent: area / area of bounding box
        minr, minc, maxr, maxc = r.bbox
        bbox_area = (maxr - minr) * (maxc - minc)
        extent = area / (bbox_area + 1e-8)

        # Intensity inside the cell (using equalized image)
        mean_int = r.mean_intensity
        max_int = getattr(r, "max_intensity", np.nan)
        min_int = getattr(r, "min_intensity", np.nan)

        intens_vals = img_eq[r.slice][r.image]  # pixels belonging to the cell
        std_int = float(np.std(intens_vals))
        median_int = float(np.median(intens_vals))

        # Local background ring around the cell
        cell_mask = np.zeros_like(masks_cp, dtype=np.uint8)
        cell_mask[lab == r.label] = 1

        kernel_size = 2 * bg_ring + 1
        kernel = cv2.getStructuringElement(
            cv2.MORPH_ELLIPSE,
            (kernel_size, kernel_size)
        )
        dilated = cv2.dilate(cell_mask, kernel, iterations=1)
        ring = (dilated == 1) & (cell_mask == 0)

        ring_vals = img_eq[ring]
        if ring_vals.size > 0:
            bg_mean = float(np.mean(ring_vals))
            bg_median = float(np.median(ring_vals))
        else:
            bg_mean = np.nan
            bg_median = np.nan

        # Derived intensity/contrast features
        contrast_mean = mean_int - bg_mean if not np.isnan(bg_mean) else np.nan
        contrast_max = max_int - bg_mean if not np.isnan(bg_mean) else np.nan
        ratio_mean = mean_int / (bg_mean + 1e-8) if not np.isnan(bg_mean) else np.nan

        # Edge intensity (mean intensity on the ring)
        if ring_vals.size > 0:
            edge_int_mean = float(np.mean(ring_vals))
        else:
            edge_int_mean = bg_mean

        # Combined "visibility" and "quality" scores
        visibility = contrast_mean * solidity if not np.isnan(contrast_mean) else np.nan
        quality_score = (
            1.0 * (contrast_mean if not np.isnan(contrast_mean) else 0.0)
            + 0.5 * (circularity if not np.isnan(circularity) else 0.0) * 100
            + 0.5 * (solidity if not np.isnan(solidity) else 0.0) * 100
        )

        cells.append({
            "label": r.label,        # Cell ID in the mask
            # Shape features
            "area": area,
            "perimeter": perimeter,
            "circularity": circularity,
            "solidity": solidity,
            "eccentricity": eccentricity,
            "major_axis": major_axis,
            "minor_axis": minor_axis,
            "aspect_ratio": aspect_ratio,
            "extent": extent,
            # Intensity features
            "mean_int": mean_int,
            "max_int": max_int,
            "min_int": min_int,
            "std_int": std_int,
            "median_int": median_int,
            # Background / contrast
            "bg_mean": bg_mean,
            "bg_median": bg_median,
            "contrast_mean": contrast_mean,
            "contrast_max": contrast_max,
            "ratio_mean": ratio_mean,
            "edge_int_mean": edge_int_mean,
            # Combined scores
            "visibility": visibility,
            "quality_score": quality_score,
        })

    df = pd.DataFrame(cells)
    return df

# ======================================================================
# 8. BUILD DATASET FOR ONE CATEGORY (SEGMENT + FEATURES + CROPS)
# ======================================================================

def build_dataset_for_category(img_dir, category_name, mu, sigma):
    """
    Segment all images in a category folder, extract cell features,
    and save raw crops for each cell.

    Parameters
    ----------
    img_dir : str
        Path to the folder containing original images of one category
        (e.g. ".../T-CELLS_DATASET/Naive").
    category_name : str
        Name of the category ("Naive", "Activated", "Exhausted").
    mu, sigma : float
        Mean and std used for intensity normalization.

    Returns
    -------
    df_cat : pandas.DataFrame
        DataFrame with one row per cell, including:
        - all features from extract_cell_features
        - filename, path, category
        - crop_raw_path: path to the raw cell crop saved on disk

    Notes
    -----
    - For each input image, we:
      1) Segment cells.
      2) Extract features.
      3) Save each cell as a separate crop in a "crops_raw" subfolder.
    """
    rows = []

    # Folder where raw crops for this category will be stored
    crops_root = os.path.join(img_dir, "crops_raw")
    os.makedirs(crops_root, exist_ok=True)

    # Loop over all image files in the category folder
    for fname in os.listdir(img_dir):
        if not fname.lower().endswith((".png", ".jpg", ".jpeg", ".tif", ".tiff")):
            continue

        path = os.path.join(img_dir, fname)

        # Segment image and compute features
        img_gray, masks_cp, img_eq = segment_image_cpsam(path, mu, sigma)
        df_img = extract_cell_features(img_gray, masks_cp, img_eq)

        # Add metadata columns
        df_img["filename"] = fname
        df_img["path"] = path
        df_img["category"] = category_name

        # Build dictionary of regions for cropping
        lab = label(masks_cp)
        regions = {r.label: r for r in regionprops(lab)}

        crop_paths = []
        base_name, _ = os.path.splitext(fname)

        # For each cell (row in df_img), create and save a crop
        for _, row in df_img.iterrows():
            cell_id = int(row["label"])

            if cell_id not in regions:
                # In case the label is missing for some reason, keep empty string
                crop_paths.append("")
                continue

            r = regions[cell_id]
            minr, minc, maxr, maxc = r.bbox
            crop = img_gray[minr:maxr, minc:maxc]

            # Build crop filename and full path
            crop_name = f"{category_name}_{base_name}_id{cell_id}.tif"
            crop_path = os.path.join(crops_root, crop_name)

            # Save crop to disk
            cv2.imwrite(crop_path, crop)

            crop_paths.append(crop_path)

        # Add crop paths to the DataFrame
        df_img["crop_raw_path"] = crop_paths

        rows.append(df_img)

    if len(rows) == 0:
        # If no images or no cells, return an empty DataFrame
        return pd.DataFrame()

    # Concatenate all per-image DataFrames into one for this category
    df_cat = pd.concat(rows, ignore_index=True)
    return df_cat

# ======================================================================
# 9. BUILD FULL DATAFRAME FOR ALL CATEGORIES (OPTIONAL)
# ======================================================================

"""
The following code shows how to:
- Build df_all (DataFrame containing all the cells) from raw images (running segmentation and feature extraction).
- Recompute circularity and quality_score (to avoid miscalculation).
In practice, this step can be very slow (Cellpose-SAM on all images),
so later we will reload df_all from an existing Excel file instead (saving it before).
"""

def build_full_dataset_from_images():
    """
    Build the complete dataset df_all by processing all category folders.

    Returns
    -------
    df_all : pandas.DataFrame
        One row per cell, with features + category + crop_raw_path.
    """
    dfs = []
    for cat in CATEGORIES:
        img_dir = os.path.join(BASE_DATASET_DIR, cat)
        print(f"[Build dataset] Processing category: {cat} -> {img_dir}")
        df_cat = build_dataset_for_category(img_dir, cat, mu, sigma)
        dfs.append(df_cat)

    df_all_local = pd.concat(dfs, ignore_index=True)

    # Recompute circularity and quality_score for consistency
    df_all_local["circularity"] = 4 * np.pi * df_all_local["area"] / (df_all_local["perimeter"]**2 + 1e-8)
    df_all_local.loc[
        (df_all_local["circularity"] < 0) | (df_all_local["circularity"] > 2),
        "circularity"
    ] = np.nan

    df_all_local["quality_score"] = (
        1.0 * df_all_local["contrast_mean"].fillna(0.0)
        + 0.5 * df_all_local["circularity"].fillna(0.0) * 100.0
        + 0.5 * df_all_local["solidity"].fillna(0.0) * 100.0
    )
    df_all_local.loc[
        (df_all_local["quality_score"] < 0) | (df_all_local["quality_score"] > 1e6),
        "quality_score"
    ] = np.nan

    return df_all_local

# Example (heavy): build and save df_all from scratch
# df_all = build_full_dataset_from_images()
# df_all.to_excel(os.path.join(STATS_DIR, "df_all.xlsx"), index=False)

# ======================================================================
# 10. LOAD EXISTING DATAFRAME df_all FROM EXCEL
# ======================================================================

"""
To avoid running Cellpose-SAM every time, we usually work from a df_all
previously saved to Excel.

- df_all: contains all cells (good + bad) with features and metadata.
- df_naive, df_activated, df_exhausted: same data filtered per category.
"""

df_all_path = os.path.join(STATS_DIR, "df_all.xlsx")
df_all = pd.read_excel(df_all_path)

df_naive = df_all[df_all["category"] == "Naive"].copy()
df_activated = df_all[df_all["category"] == "Activated"].copy()
df_exhausted = df_all[df_all["category"] == "Exhausted"].copy()

# ======================================================================
# 11. LOAD MANUAL ANNOTATIONS (GOOD/BAD LABELS)
# ======================================================================

"""
Manual annotations are stored in three CSV files, one per category.
Each file includes at least:
- the same cell identifier/path used in df_all,
- a column "manual_label" with values "good" or "bad".

parla del file dove hai segmentato e selezionato le cellule good e bad

We load them, add the category column, and concatenate into df_all_manual.
"""

# Folder with manual annotation CSVs
annot_base = MANUAL_ANNOT_DIR

# Naive
df_naive_man = pd.read_csv(
    os.path.join(annot_base, "annotazioni_manuali_naive", "annotazioni_manuali_naive.csv")
)
df_naive_man["category"] = "Naive"

# Activated
df_activated_man = pd.read_csv(
    os.path.join(annot_base, "annotazioni_manuali_activated", "annotazioni_manuali_activated.csv")
)
df_activated_man["category"] = "Activated"

# Exhausted
df_exhausted_man = pd.read_csv(
    os.path.join(annot_base, "annotazioni_manuali_exhausted", "annotazioni_manuali_exhausted.csv")
)
df_exhausted_man["category"] = "Exhausted"

# Concatenate all manual annotation tables
df_all_manual = pd.concat(
    [df_naive_man, df_activated_man, df_exhausted_man],
    ignore_index=True
)

print("[Manual annotations] Shape:", df_all_manual.shape)
print("[Manual annotations] Columns:", df_all_manual.columns.tolist())

# ======================================================================
# 12. DEFINE FEATURE COLUMNS FOR QUALITY MODEL (GOOD vs BAD)
# ======================================================================

"""
We now define the list of feature columns that we will use for:
- training the good/bad (quality) models,
- and later for the category models.

These features come from extract_cell_features and describe shape and
intensity/contrast properties of each cell.
"""

feature_cols = [
    "area", "perimeter", "circularity", "solidity", "eccentricity",
    "major_axis", "minor_axis", "aspect_ratio", "extent",
    "mean_int", "max_int", "min_int", "std_int",
    "median_int", "bg_mean", "bg_median", "contrast_mean",
    "contrast_max", "ratio_mean", "edge_int_mean", "visibility",
    "quality_score",
]

# Build feature matrix X and label vector y for quality model
# manual_label: "bad" -> 0, "good" -> 1
X = df_all_manual[feature_cols].values
y = df_all_manual["manual_label"].map({"bad": 0, "good": 1}).values

# Features for all cells (good + bad) from df_all (used later to extend predictions)
X_all = df_all[feature_cols].values

# ======================================================================
# 13. TRAIN/TEST SPLIT FOR QUALITY MODEL (GOOD vs BAD)
# ======================================================================

"""
We split the manually annotated dataset into training and test sets.
The split is stratified to preserve the proportion of good/bad labels.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42,
)

# ======================================================================
# 14. LOGISTIC REGRESSION MODEL (GOOD vs BAD)
# ======================================================================

"""
We build a Pipeline that:
1) Imputes missing values using the median.
2) Standardizes features (zero mean, unit variance).
3) Trains a Logistic Regression with L2 regularization.

We then:
- compute probabilities on the test set,
- apply a threshold (e.g. 0.7) to decide good vs bad,
- and print a classification report.
"""

log_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        penalty="l2",
        C=0.4,
        solver="lbfgs",
        max_iter=1000,
    )),
])

log_model.fit(X_train, y_train)

y_prob_log = log_model.predict_proba(X_test)[:, 1]  # probability of class "good"
threshold_log = 0.7  # can be tuned (e.g. 0.6, 0.8...)
y_pred_log = (y_prob_log >= threshold_log).astype(int)

print("=== Logistic Regression (good vs bad, test set) ===")
print(classification_report(y_test, y_pred_log, target_names=["bad", "good"]))

# Save Logistic Regression classification report to Excel
log_reg_creport = classification_report(
    y_test,
    y_pred_log,
    target_names=["bad", "good"],
    output_dict=True,
)
df_report_log = pd.DataFrame(log_reg_creport).T
df_report_log.to_excel(
    os.path.join(STATS_DIR, "Creport_logistic_reg_test_goodbad.xlsx"),
    index=True,
)

# ======================================================================
# 15. RANDOM FOREST MODEL (GOOD vs BAD)
# ======================================================================

"""
We build another Pipeline that:
1) Imputes missing values using the mean.
2) Standardizes features (for consistency).
3) Trains a RandomForest with 150 trees and limited depth.

We then:
- compute probabilities on the test set,
- apply a more conservative threshold (e.g. 0.8),
- and print a classification report.
"""

rf_model = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler()),
    ("rf", RandomForestClassifier(
        n_estimators=150,
        max_depth=8,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1,
    )),
])

rf_model.fit(X_train, y_train)

y_prob_rf = rf_model.predict_proba(X_test)[:, 1]  # probability of class "good"
threshold_rf = 0.8  # stricter threshold for classifying as good
y_pred_rf = (y_prob_rf >= threshold_rf).astype(int)

print("=== Random Forest (good vs bad, test set) ===")
print(classification_report(y_test, y_pred_rf, target_names=["bad", "good"]))

# Save Random Forest classification report to Excel
rf_creport = classification_report(
    y_test,
    y_pred_rf,
    target_names=["bad", "good"],
    output_dict=True,
)
df_report_rf = pd.DataFrame(rf_creport).T
df_report_rf.to_excel(
    os.path.join(STATS_DIR, "report_randomforest_test_goodbad.xlsx"),
    index=True,
)

# ======================================================================
# 16. LEARNING CURVES FOR GOOD/BAD MODELS
# ======================================================================

def plot_learning_curve(model, X, y, title):
    """
    Compute and display the learning curve of a model.

    The learning curve shows how training and validation accuracy evolve
    as we increase the training set size. It helps to understand if the
    model is underfitting or overfitting.

    Parameters
    ----------
    model : sklearn estimator or Pipeline
        The model to evaluate.
    X : np.ndarray
        Feature matrix.
    y : np.ndarray
        Labels.
    title : str
        Plot title.
    """
    train_sizes, train_scores, val_scores = learning_curve(
        model,
        X,
        y,
        cv=5,
        scoring="accuracy",
        train_sizes=np.linspace(0.1, 1.0, 5),
        n_jobs=-1,
        shuffle=True,
        random_state=42,
    )

    train_mean = train_scores.mean(axis=1)
    train_std = train_scores.std(axis=1)
    val_mean = val_scores.mean(axis=1)
    val_std = val_scores.std(axis=1)

    plt.figure(figsize=(6, 4))
    plt.plot(train_sizes, train_mean, "o-", label="train", color="tab:blue")
    plt.fill_between(
        train_sizes,
        train_mean - train_std,
        train_mean + train_std,
        alpha=0.2,
        color="tab:blue",
    )
    plt.plot(train_sizes, val_mean, "o-", label="validation", color="tab:orange")
    plt.fill_between(
        train_sizes,
        val_mean - val_std,
        val_mean + val_std,
        alpha=0.2,
        color="tab:orange",
    )
    plt.xlabel("Number of training samples")
    plt.ylabel("Accuracy")
    plt.title(title)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Use the full manually annotated dataset (X, y) for learning curves
plot_learning_curve(log_model, X, y, "Learning curve Logistic Regression (good vs bad)")
plot_learning_curve(rf_model, X, y, "Learning curve Random Forest (good vs bad)")

# ======================================================================
# 17. ENSEMBLE (LOGISTIC + RF) FOR GOOD/BAD
# ======================================================================

"""
We combine Logistic Regression and Random Forest by averaging their
predicted probabilities for the "good" class.

This simple ensemble often improves robustness. We then apply a single
threshold (e.g. 0.8) on the combined probability.
"""

# Probabilities on test set
y_prob_log_test = log_model.predict_proba(X_test)[:, 1]
y_prob_rf_test = rf_model.predict_proba(X_test)[:, 1]

# Simple average ensemble
y_prob_comb_test = 0.5 * y_prob_log_test + 0.5 * y_prob_rf_test
threshold_ensemble = 0.8
y_pred_comb_test = (y_prob_comb_test >= threshold_ensemble).astype(int)

print("=== Ensemble Logistic + Random Forest (good vs bad, test set) ===")
print(classification_report(y_test, y_pred_comb_test, target_names=["bad", "good"]))

# ======================================================================
# 18. APPLY QUALITY MODEL TO MANUALLY ANNOTATED DF (df_all_manual)
# ======================================================================

"""
We now apply the ensemble model to all manually annotated cells to:
- store the combined probability of being "good",
- store the predicted label (0/1 and "good"/"bad").
"""

y_prob_log_manual = log_model.predict_proba(X)[:, 1]
y_prob_rf_manual = rf_model.predict_proba(X)[:, 1]
y_prob_comb_manual = 0.5 * y_prob_log_manual + 0.5 * y_prob_rf_manual

threshold_quality = 0.8

df_all_manual["p_good_comb"] = y_prob_comb_manual
df_all_manual["pred_comb"] = (y_prob_comb_manual >= threshold_quality).astype(int)
df_all_manual["label_comb"] = df_all_manual["pred_comb"].map({0: "bad", 1: "good"})

# ======================================================================
# 19. APPLY QUALITY MODEL TO ALL CELLS (df_all)
# ======================================================================

"""
Using the same ensemble model, we predict good/bad for all cells in df_all
(not only those with manual labels).

We store:
- p_good_comb: probability of being "good",
- pred_comb: binary prediction (0/1),
- label_comb: "bad" or "good".

We also save the resulting DataFrame to Excel.
"""

df_all_pred = df_all.copy()
df_all_pred.to_excel(os.path.join(STATS_DIR, "df_all_pred_before_quality.xlsx"), index=False)

# Probabilities for all cells
y_prob_log_all = log_model.predict_proba(X_all)[:, 1]
y_prob_rf_all = rf_model.predict_proba(X_all)[:, 1]
y_prob_comb_all = 0.5 * y_prob_log_all + 0.5 * y_prob_rf_all

df_all_pred["p_good_comb"] = y_prob_comb_all
df_all_pred["pred_comb"] = (y_prob_comb_all >= threshold_quality).astype(int)
df_all_pred["label_comb"] = df_all_pred["pred_comb"].map({0: "bad", 1: "good"})

# Save predictions to Excel
df_all_pred.to_excel(os.path.join(STATS_DIR, "df_all_prediction_goodbad.xlsx"), index=False)

# For convenience, make sure we have a crop_path column initialized
if "crop_path" not in df_all_pred.columns:
    df_all_pred["crop_path"] = df_all_pred.get("crop_raw_path", None)

# ======================================================================
# 20. ORGANIZE CROPS INTO GOOD/BAD SUBFOLDERS
# ======================================================================

def organize_crops_good_bad(
    df,
    label_col="label_comb",  # or "pred_comb" if you want 0/1
    base_label_is_prob=False,
):
    """
    Move raw cell crops into "good" and "bad" subfolders based on a label.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame containing at least:
        - 'crop_raw_path': path to the raw crop,
        - label_col: either "good"/"bad" or 0/1.
    label_col : str, optional
        Column name containing labels used to split cells.
    base_label_is_prob : bool, optional
        If True, interpret label_col as 0/1 and map to "good"/"bad".

    Returns
    -------
    df_out : pandas.DataFrame
        Copy of df with an updated "crop_path" column indicating the
        final path of each crop (in "good" or "bad" subfolder).

    Notes
    -----
    - For each crop:
      1) Determine its label ("good" or "bad").
      2) Move it into the corresponding subfolder inside its original
         "crops_raw" directory.
    """
    df_out = df.copy()

    if "crop_path" not in df_out.columns:
        df_out["crop_path"] = None

    for idx, row in df_out.iterrows():
        src = row.get("crop_raw_path")
        if not isinstance(src, str) or not os.path.exists(src):
            continue

        lab = row.get(label_col)
        if base_label_is_prob:
            lab = "good" if lab == 1 else "bad"
        else:
            lab = str(lab).lower()

        if lab not in ["good", "bad"]:
            continue

        # Original crops_raw directory (e.g. .../Naive/crops_raw)
        cropsraw_dir = os.path.dirname(src)
        good_dir = os.path.join(cropsraw_dir, "good")
        bad_dir = os.path.join(cropsraw_dir, "bad")

        os.makedirs(good_dir, exist_ok=True)
        os.makedirs(bad_dir, exist_ok=True)

        dst_dir = good_dir if lab == "good" else bad_dir

        fname = os.path.basename(src)
        dst = os.path.join(dst_dir, fname)

        shutil.move(src, dst)
        df_out.at[idx, "crop_path"] = dst

    return df_out

# Apply organization of crops
df_all_pred_with_crops = organize_crops_good_bad(
    df_all_pred,
    label_col="label_comb",
    base_label_is_prob=False,
)
df_all_pred_with_crops.to_excel(
    os.path.join(STATS_DIR, "df_all_pred_with_crops_goodbad.xlsx"),
    index=False,
)

# Save list of "good" cells only
df_good_cells = df_all_pred_with_crops[df_all_pred_with_crops["label_comb"] == "good"].copy()
df_good_cells.to_excel(os.path.join(STATS_DIR, "df_good_cells.xlsx"), index=False)

# ======================================================================
# 21. FEATURE IMPORTANCE (GOOD vs BAD)
# ======================================================================

"""
We inspect which features are most important for the good/bad decision,
using:
- Logistic Regression coefficients,
- Random Forest feature importance,
and a combined rank.
"""

# Logistic Regression coefficients (after pipeline)
log_coefs = log_model.named_steps["logreg"].coef_[0]

df_importance_feat = pd.DataFrame({
    "feature": feature_cols,
    "log_coef": log_coefs,
    "log_abs_coef": np.abs(log_coefs),
})

# Random Forest feature importances
rf_importance = rf_model.named_steps["rf"].feature_importances_
df_importance_feat["rf_importance"] = rf_importance

# Separate ranks (1 = most important)
df_importance_feat["rank_log"] = df_importance_feat["log_abs_coef"].rank(
    ascending=False,
    method="min",
)
df_importance_feat["rank_rf"] = df_importance_feat["rf_importance"].rank(
    ascending=False,
    method="min",
)

# Combined rank = sum of individual ranks
df_importance_feat["combined_rank"] = (
    df_importance_feat["rank_log"] + df_importance_feat["rank_rf"]
)

df_final_importance = df_importance_feat[
    ["feature", "log_coef", "log_abs_coef", "rf_importance", "combined_rank"]
].sort_values("combined_rank")

df_final_importance.to_excel(
    os.path.join(STATS_DIR, "Importance_feature_LR_RF_goodbad.xlsx"),
    index=False,
)

# ======================================================================
# 22. RELOAD GOOD CELLS (IF NEEDED) AND PREPARE FOR PCA / t-SNE
# ======================================================================

"""
We load df_good_cells (if not already in memory) and prepare the feature
matrix for dimensionality reduction (PCA and t-SNE).
"""

df_good_cells_path = os.path.join(STATS_DIR, "df_good_cells.xlsx")
df_good_cells = pd.read_excel(df_good_cells_path)

# Feature matrix and category labels for good cells
X_good = df_good_cells[feature_cols].values
y_cat = df_good_cells["category"].values

# Impute missing values and standardize
imputer = SimpleImputer(strategy="median")
X_good_imp = imputer.fit_transform(X_good)

scaler = StandardScaler()
X_good_scaled = scaler.fit_transform(X_good_imp)

# ======================================================================
# 23. PCA ON GOOD CELLS (ALL CATEGORIES)
# ======================================================================

"""
We run PCA on good cells to understand how categories separate in a
lower-dimensional space.

- We use 8 principal components.
- We visualize PC1 vs PC2 colored by category.
"""

pca = PCA(n_components=8, random_state=42)
X_pca = pca.fit_transform(X_good_scaled)

# Scatter plot PC1 vs PC2 by category
plt.figure(figsize=(6, 5))
for cat in np.unique(y_cat):
    mask = (y_cat == cat)
    plt.scatter(
        X_pca[mask, 0],
        X_pca[mask, 1],
        s=20,
        alpha=0.7,
        label=cat,
    )

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA - good cells by category")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Explained variance ratio for each PC
expl_var = pca.explained_variance_ratio_

plt.figure(figsize=(6, 4))
plt.bar(range(1, len(expl_var) + 1), expl_var)
plt.xlabel("Principal components")
plt.ylabel("Explained variance ratio")
plt.title("Explained variance by each principal component")
plt.xticks(range(1, len(expl_var) + 1))
plt.tight_layout()
plt.show()

# Loadings: how much each feature contributes to each PC
loadings = pca.components_  # shape: (n_components, n_features)
pc_names = [f"PC{i}" for i in range(1, len(expl_var) + 1)]

df_loadings = pd.DataFrame(
    loadings,
    index=pc_names,
    columns=feature_cols,
)
display(df_loadings)
df_loadings.to_excel(
    os.path.join(STATS_DIR, "Loadings_PCA_goodcells.xlsx"),
    index=True,
)

# Cumulative explained variance
cum_expl_var = np.cumsum(expl_var)
plt.figure(figsize=(6, 4))
plt.plot(range(1, len(cum_expl_var) + 1), cum_expl_var, "o-")
plt.xlabel("Principal components")
plt.ylabel("Cumulative explained variance")
plt.title("Cumulative explained variance (PCA on good cells)")
plt.grid(True)
plt.tight_layout()
plt.show()

# ======================================================================
# 24. TOP LOADINGS FOR FIRST 3 PCs + 3D PCA PLOT
# ======================================================================

# Focus on first 3 PCs for interpretability
df_loadings_3 = pd.DataFrame(
    pca.components_[:3],
    index=[f"PC{i}" for i in range(1, 4)],
    columns=feature_cols,
)

# Print top-15 features (by absolute loading) for each PC
for pc in df_loadings_3.index:
    print(pc)
    print(df_loadings_3.loc[pc].abs().sort_values(ascending=False).head(15))
    print()

# Build table with top-15 features for each PC (for saving)
rows_top = []
for pc in df_loadings_3.index:
    serie = df_loadings_3.loc[pc]
    topk = serie.abs().sort_values(ascending=False).head(15)
    for feat in topk.index:
        rows_top.append({
            "PC": pc,
            "feature": feat,
            "loading": serie[feat],
            "abs_loading": abs(serie[feat]),
        })

df_top_loadings = pd.DataFrame(rows_top).sort_values(
    ["PC", "abs_loading"],
    ascending=[True, False],
)
df_top_loadings.to_excel(
    os.path.join(STATS_DIR, "Top_loadings_PCA_first3_goodcells.xlsx"),
    index=False,
)

# 3D PCA scatter (PC1, PC2, PC3) colored by category
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

X_pca3 = X_pca[:, :3]

fig = plt.figure(figsize=(6, 5))
ax = fig.add_subplot(111, projection="3d")

for cat in np.unique(y_cat):
    mask = (y_cat == cat)
    ax.scatter(
        X_pca3[mask, 0],  # PC1
        X_pca3[mask, 1],  # PC2
        X_pca3[mask, 2],  # PC3
        s=20,
        alpha=0.7,
        label=cat,
    )

ax.set_xlabel("PC1")
ax.set_ylabel("PC2")
ax.set_zlabel("PC3")
ax.legend()
plt.tight_layout()
plt.show()

# Optional: bar plots of feature contributions for PC1, PC2, PC3
for pc in ["PC1", "PC2", "PC3"]:
    plt.figure(figsize=(8, 4))
    df_loadings_3.loc[pc].plot(kind="bar")
    plt.ylabel("Loading")
    plt.title(f"Feature contributions to {pc}")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()

# ======================================================================
# 25. t-SNE ON GOOD CELLS (ALL CATEGORIES)
# ======================================================================

"""
We apply t-SNE to the standardized good-cell features to visualize
non-linear structure and possible clustering by category.
"""

tsne = TSNE(
    n_components=2,
    perplexity=30,
    learning_rate=200,
    n_iter=1000,
    random_state=42,
)

X_tsne = tsne.fit_transform(X_good_scaled)

plt.figure(figsize=(6, 5))
for cat in np.unique(y_cat):
    mask = (y_cat == cat)
    plt.scatter(
        X_tsne[mask, 0],
        X_tsne[mask, 1],
        s=20,
        alpha=0.7,
        label=cat,
    )

plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.title("t-SNE - good cells by category")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# ======================================================================
# 26. PCA + t-SNE FOR PAIRS OF CATEGORIES (GOOD CELLS ONLY)
# ======================================================================

"""
To better understand differences between pairs of categories,
we run PCA and t-SNE separately for each pair:
- Naive vs Activated
- Naive vs Exhausted
- Activated vs Exhausted
"""

pairs = [
    ("Naive", "Activated"),
    ("Naive", "Exhausted"),
    ("Activated", "Exhausted"),
]

results_pairs = []
rows_load_pairs = []

for c1, c2 in pairs:
    df_pair = df_good_cells[df_good_cells["category"].isin([c1, c2])].copy()
    X_pair = df_pair[feature_cols].values
    y_pair = df_pair["category"].values

    imputer_pair = SimpleImputer(strategy="mean")
    X_pair_imp = imputer_pair.fit_transform(X_pair)

    scaler_pair = StandardScaler()
    X_pair_scaled = scaler_pair.fit_transform(X_pair_imp)

    print(c1, "vs", c2, " -> n =", X_pair_scaled.shape[0])

    # ===== PCA with 6 components =====
    pca_pair = PCA(n_components=6, random_state=42)
    X_pca_pair = pca_pair.fit_transform(X_pair_scaled)
    expl_pair = pca_pair.explained_variance_ratio_

    results_pairs.append({
        "pair": f"{c1} vs {c2}",
        "PC1_var": expl_pair[0],
        "PC2_var": expl_pair[1],
        "PC3_var": expl_pair[2],
        "PC4_var": expl_pair[3],
        "PC5_var": expl_pair[4],
        "PC6_var": expl_pair[5],
        "PC1-6_var_sum": expl_pair[:6].sum(),
    })

    # Centroids on PC1-PC2 for each category
    df_scores_pair = pd.DataFrame(X_pca_pair[:, :2], columns=["PC1", "PC2"])
    df_scores_pair["category"] = y_pair
    centroids = df_scores_pair.groupby("category")[["PC1", "PC2"]].mean()

    for cat in [c1, c2]:
        results_pairs[-1][f"PC1_mean_{cat}"] = centroids.loc[cat, "PC1"]
        results_pairs[-1][f"PC2_mean_{cat}"] = centroids.loc[cat, "PC2"]

    # Top loadings for the first 6 PCs
    load_df_pair = pd.DataFrame(
        pca_pair.components_,
        index=[f"PC{i}" for i in range(1, 7)],
        columns=feature_cols,
    )

    for pc in load_df_pair.index:
        serie = load_df_pair.loc[pc]
        topk = serie.abs().sort_values(ascending=False).head(5)
        for feat in topk.index:
            rows_load_pairs.append({
                "pair": f"{c1} vs {c2}",
                "PC": pc,
                "feature": feat,
                "loading": serie[feat],
                "abs_loading": abs(serie[feat]),
            })

    # ===== Plot PCA (PC1 vs PC2) =====
    plt.figure(figsize=(5, 4))
    for cat, color in zip([c1, c2], ["tab:blue", "tab:orange"]):
        mask = (y_pair == cat)
        plt.scatter(
            X_pca_pair[mask, 0],
            X_pca_pair[mask, 1],
            s=20,
            alpha=0.7,
            label=cat,
            color=color,
        )
    plt.xlabel("PC1")
    plt.ylabel("PC2")
    plt.title(f"PCA: {c1} vs {c2} (good cells only)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    # ===== t-SNE for the pair =====
    tsne_pair = TSNE(
        n_components=2,
        perplexity=30,
        learning_rate=200,
        n_iter=1000,
        random_state=42,
    )
    X_tsne_pair = tsne_pair.fit_transform(X_pair_scaled)

    plt.figure(figsize=(5, 4))
    for cat, color in zip([c1, c2], ["tab:blue", "tab:orange"]):
        mask = (y_pair == cat)
        plt.scatter(
            X_tsne_pair[mask, 0],
            X_tsne_pair[mask, 1],
            s=20,
            alpha=0.7,
            label=cat,
            color=color,
        )
    plt.xlabel("t-SNE 1")
    plt.ylabel("t-SNE 2")
    plt.title(f"t-SNE: {c1} vs {c2} (good cells only)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Save PCA pair statistics and loadings
df_pairs_stats = pd.DataFrame(results_pairs)
df_pairs_stats.to_excel(
    os.path.join(STATS_DIR, "PCA_pairs_stats_6PC_goodcells.xlsx"),
    index=False,
)

df_pairs_loadings = pd.DataFrame(rows_load_pairs).sort_values(
    ["pair", "PC", "abs_loading"],
    ascending=[True, True, False],
)
df_pairs_loadings.to_excel(
    os.path.join(STATS_DIR, "PCA_pairs_toploadings_6PC_goodcells.xlsx"),
    index=False,
)

# Optional: per-pair bar plots of explained variance and top loadings
stats_pairs = pd.read_excel(
    os.path.join(STATS_DIR, "PCA_pairs_stats_6PC_goodcells.xlsx")
)
for pair in stats_pairs["pair"]:
    row = stats_pairs[stats_pairs["pair"] == pair].iloc[0]
    expl = [row[f"PC{i}_var"] for i in range(1, 7)]
    plt.figure(figsize=(4, 3))
    plt.bar(range(1, 7), expl)
    plt.xlabel("Principal components")
    plt.ylabel("Explained variance")
    plt.title(f"{pair}: explained variance (PC1–PC6)")
    plt.ylim(0, max(expl) * 1.2)
    plt.tight_layout()
    plt.show()

loads_pairs = pd.read_excel(
    os.path.join(STATS_DIR, "PCA_pairs_toploadings_6PC_goodcells.xlsx")
)
for pair in loads_pairs["pair"].unique():
    for pc in ["PC1", "PC2"]:
        sub = loads_pairs[
            (loads_pairs["pair"] == pair) & (loads_pairs["PC"] == pc)
        ]
        sub = sub.sort_values("abs_loading", ascending=False).head(10)
        plt.figure(figsize=(5, 3))
        plt.bar(sub["feature"], sub["loading"])
        plt.xticks(rotation=45, ha="right")
        plt.ylabel("Loading")
        plt.title(f"{pair} – {pc}: top features")
        plt.tight_layout()
        plt.show()

# ======================================================================
# 27. MULTICLASS MODELS (Naive / Activated / Exhausted) ON GOOD CELLS
# ======================================================================

"""
We now train models to classify the category of a cell (Naive, Activated,
Exhausted) using only cells that were predicted as "good" quality.

We build:
- a multinomial Logistic Regression model,
- a Random Forest classifier,
and an ensemble that averages their probabilities.
"""

df_good_cells = pd.read_excel(df_good_cells_path)

dataframe_good_with_category = df_good_cells.copy()
feature_matrix = dataframe_good_with_category[feature_cols].values
label_vector = dataframe_good_with_category["category"].values

(
    feature_train,
    feature_test,
    label_train,
    label_test,
) = train_test_split(
    feature_matrix,
    label_vector,
    test_size=0.2,
    random_state=42,
    stratify=label_vector,
)

# Pipeline 1: Multinomial Logistic Regression
pipeline_cat_logreg = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        (
            "logreg_multiclass",
            LogisticRegression(
                multi_class="multinomial",
                max_iter=2000,
                class_weight="balanced",
            ),
        ),
    ]
)

# Pipeline 2: Random Forest multiclass
pipeline_cat_rf = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        (
            "rf_multiclass",
            RandomForestClassifier(
                n_estimators=200,
                max_depth=None,
                min_samples_leaf=2,
                random_state=42,
                n_jobs=-1,
                class_weight=None,
            ),
        ),
    ]
)

# Train both models
pipeline_cat_logreg.fit(feature_train, label_train)
pipeline_cat_rf.fit(feature_train, label_train)

# Evaluate on test set
class_names = ["Activated", "Exhausted", "Naive"]

print("=== Logistic Regression multiclasse ===")
vettore_predizioni_test_logreg = pipeline_classificatore_categoria_linfociti_logreg.predict(
    matrice_feature_test
)

print(classification_report(vettore_etichette_test, vettore_predizioni_test_logreg))
cm_logreg = confusion_matrix(vettore_etichette_test, vettore_predizioni_test_logreg,
                             labels=class_names)

disp_logreg = ConfusionMatrixDisplay(confusion_matrix=cm_logreg,
                                     display_labels=class_names)
disp_logreg.plot(cmap="Blues", values_format="d")
plt.xlabel("Predetto")
plt.ylabel("Vero")
plt.title("Matrice di confusione – Logistic Regression")
plt.tight_layout()
plt.show()

print("\n=== Random Forest multiclasse ===")
vettore_predizioni_test_rf = pipeline_classificatore_categoria_linfociti_random_forest.predict(
    matrice_feature_test
)

print(classification_report(vettore_etichette_test, vettore_predizioni_test_rf))
cm_rf = confusion_matrix(vettore_etichette_test, vettore_predizioni_test_rf,
                         labels=class_names)

disp_rf = ConfusionMatrixDisplay(confusion_matrix=cm_rf,
                                 display_labels=class_names)
disp_rf.plot(cmap="Blues", values_format="d")
plt.xlabel("Predetto")
plt.ylabel("Vero")
plt.title("Matrice di confusione – Random Forest")
plt.tight_layout()
plt.show()
# Save classification reports to Excel
report_logreg_cat = classification_report(
    label_test,
    pred_test_logreg,
    output_dict=True,
)
df_report_logreg_cat = pd.DataFrame(report_logreg_cat).T
df_report_logreg_cat.to_excel(
    os.path.join(STATS_DIR, "classification_report_logreg_category.xlsx"),
    index=True,
)

report_rf_cat = classification_report(
    label_test,
    pred_test_rf,
    output_dict=True,
)
df_report_rf_cat = pd.DataFrame(report_rf_cat).T
df_report_rf_cat.to_excel(
    os.path.join(STATS_DIR, "classification_report_random_forest_category.xlsx"),
    index=True,
)

# Ensemble probabilities on test set
proba_logreg_test_cat = pipeline_cat_logreg.predict_proba(feature_test)
proba_rf_test_cat = pipeline_cat_rf.predict_proba(feature_test)

proba_ensemble_test_cat = 0.5 * proba_logreg_test_cat + 0.5 * proba_rf_test_cat
pred_indices_ensemble = proba_ensemble_test_cat.argmax(axis=1)

class_labels = pipeline_cat_logreg.classes_
pred_test_ensemble_labels = class_labels[pred_indices_ensemble]

print("=== Ensemble Logistic + Random Forest (category, test set) ===")
print(classification_report(label_test, pred_test_ensemble_labels))
print(confusion_matrix(label_test, pred_test_ensemble_labels))

# Save trained category models
model_cat_logreg_path = os.path.join(STATS_DIR, "model_category_logreg.pkl")
model_cat_rf_path = os.path.join(STATS_DIR, "model_category_random_forest.pkl")

joblib.dump(pipeline_cat_logreg, model_cat_logreg_path)
joblib.dump(pipeline_cat_rf, model_cat_rf_path)

# ======================================================================
# 28. FULL PIPELINE ON A NEW FOLDER OF IMAGES
# ======================================================================

def build_good_cells_dataframe_from_folder(
    images_dir,
    mu,
    sigma,
    goodbad_log_model,
    goodbad_rf_model,
    good_threshold=0.75,
    feature_list=None,
):
    """
    Segment all images in a folder, compute cell features, and keep only
    cells predicted as "good" by the ensemble of good/bad models.

    Parameters
    ----------
    images_dir : str
        Path to the folder containing the NEW brightfield images to process.
    mu, sigma : float
        Mean and std used for intensity normalization (same as training).
    goodbad_log_model : sklearn Pipeline
        Trained Logistic Regression pipeline for good/bad.
    goodbad_rf_model : sklearn Pipeline
        Trained Random Forest pipeline for good/bad.
    good_threshold : float, default=0.75
        Threshold on the combined probability to classify a cell as "good".
    feature_list : list of str, optional
        Names of feature columns used by the quality models. If None,
        use the global feature_cols defined earlier.

    Returns
    -------
    df_good_new : pandas.DataFrame
        DataFrame with one row per "good" cell, including features and
        metadata (filename, path, etc.).

    Notes
    -----
    - This function does NOT classify categories (Naive/Activated/Exhausted).
      It only keeps high-quality cells.
    - You typically call this first, then apply category models to df_good_new.
    """
    if feature_list is None:
        feature_list = feature_cols

    all_rows = []

    for fname in os.listdir(images_dir):
        if not fname.lower().endswith((".png", ".jpg", ".jpeg", ".tif", ".tiff")):
            continue

        img_path = os.path.join(images_dir, fname)
        print(f"[New folder] Processing image: {img_path}")

        # Segment and compute features
        img_gray, masks_cp, img_eq = segment_image_cpsam(img_path, mu, sigma)
        df_img = extract_cell_features(img_gray, masks_cp, img_eq)

        # Add minimal metadata for traceability
        df_img["filename"] = fname
        df_img["path"] = img_path

        if df_img.empty:
            continue

        # Matrix of features for quality model
        X_new = df_img[feature_list].values

        # Good/bad probabilities from both models
        prob_log = goodbad_log_model.predict_proba(X_new)[:, 1]
        prob_rf = goodbad_rf_model.predict_proba(X_new)[:, 1]
        prob_comb = 0.5 * prob_log + 0.5 * prob_rf

        # Decide if each cell is "good"
        df_img["p_good_comb"] = prob_comb
        df_img["pred_good"] = (prob_comb >= good_threshold).astype(int)
        df_img["label_good"] = df_img["pred_good"].map({0: "bad", 1: "good"})

        all_rows.append(df_img)

    if len(all_rows) == 0:
        print("[New folder] No cells found or no valid images.")
        return pd.DataFrame()

    df_all_new = pd.concat(all_rows, ignore_index=True)
    df_good_new = df_all_new[df_all_new["label_good"] == "good"].copy()

    print(f"[New folder] Total cells: {df_all_new.shape[0]}, good cells: {df_good_new.shape[0]}")
    return df_good_new


def run_full_pipeline_on_folder(
    images_dir,
    output_excel_path,
    mu,
    sigma,
    goodbad_log_model,
    goodbad_rf_model,
    cat_log_model,
    cat_rf_model,
    good_threshold=0.75,
    feature_list=None,
):
    """
    Run the full pipeline on a new folder of images:
    1. Segment images and compute features.
    2. Use good/bad ensemble to filter high-quality cells.
    3. Use category models to classify each good cell as Naive/Activated/Exhausted.
    4. Save the final DataFrame to an Excel file.

    Parameters
    ----------
    images_dir : str
        Path to the folder containing the NEW brightfield images.
    output_excel_path : str
        Full path to the Excel file where results will be saved.
    mu, sigma : float
        Mean and std for intensity normalization (same as training).
    goodbad_log_model : sklearn Pipeline
        Trained Logistic Regression pipeline for good/bad.
    goodbad_rf_model : sklearn Pipeline
        Trained Random Forest pipeline for good/bad.
    cat_log_model : sklearn Pipeline
        Trained Logistic Regression pipeline for category classification.
    cat_rf_model : sklearn Pipeline
        Trained Random Forest pipeline for category classification.
    good_threshold : float, default=0.75
        Threshold on the combined good/bad probability.
    feature_list : list of str, optional
        Feature names used by models. If None, uses global feature_cols.

    Returns
    -------
    df_results : pandas.DataFrame
        Final DataFrame with only good cells, including:
        - all features,
        - p_good_comb, label_good,
        - category predictions: logreg, RF, ensemble.

    Usage
    -----
    1. Load trained models from disk:
         goodbad_log_model = log_model
         goodbad_rf_model  = rf_model
         cat_log_model     = joblib.load(model_cat_logreg_path)
         cat_rf_model      = joblib.load(model_cat_rf_path)

    2. Call the function:
         run_full_pipeline_on_folder(
             images_dir=NEW_IMAGES_DIR_1,
             output_excel_path=os.path.join(STATS_DIR, "new_folder_results.xlsx"),
             mu=mu,
             sigma=sigma,
             goodbad_log_model=goodbad_log_model,
             goodbad_rf_model=goodbad_rf_model,
             cat_log_model=cat_log_model,
             cat_rf_model=cat_rf_model,
             good_threshold=0.75,
         )
    """
    if feature_list is None:
        feature_list = feature_cols

    # Step 1-2: segment, extract features, filter good cells
    df_good_new = build_good_cells_dataframe_from_folder(
        images_dir=images_dir,
        mu=mu,
        sigma=sigma,
        goodbad_log_model=goodbad_log_model,
        goodbad_rf_model=goodbad_rf_model,
        good_threshold=good_threshold,
        feature_list=feature_list,
    )

    if df_good_new.empty:
        print("[Full pipeline] No good cells found. Nothing to classify.")
        return df_good_new

    # Step 3: category classification on good cells
    X_new_good = df_good_new[feature_list].values

    proba_log_cat = cat_log_model.predict_proba(X_new_good)
    proba_rf_cat = cat_rf_model.predict_proba(X_new_good)

    # Individual predictions
    pred_log_cat = cat_log_model.predict(X_new_good)
    pred_rf_cat = cat_rf_model.predict(X_new_good)

    # Ensemble of category probabilities
    proba_ensemble_cat = 0.5 * proba_log_cat + 0.5 * proba_rf_cat
    pred_idx_ensemble_cat = proba_ensemble_cat.argmax(axis=1)
    ensemble_classes = cat_log_model.classes_
    pred_ensemble_cat = ensemble_classes[pred_idx_ensemble_cat]

    # Store predictions in the DataFrame
    df_good_new["pred_category_logreg"] = pred_log_cat
    df_good_new["pred_category_rf"] = pred_rf_cat
    df_good_new["pred_category_ensemble"] = pred_ensemble_cat

    # Step 4: save to Excel
    os.makedirs(os.path.dirname(output_excel_path), exist_ok=True)
    df_good_new.to_excel(output_excel_path, index=False)

    print(f"[Full pipeline] Saved results to: {output_excel_path}")
    return df_good_new

# ======================================================================
# 29. EXAMPLE: HOW A USER RUNS THE SCRIPT
# ======================================================================

"""
Below is a minimal example that a user can follow.

"""

"""
# 1) Adjust paths in the USER CONFIGURATION section (e.g. BASE_DATASET_DIR).

# 2) Make sure df_all.xlsx, df_all_manual, and df_good_cells.xlsx exist
#    (you may have created them in a previous run).

# 3) Run the script top to bottom to:
#    - train good/bad models,
#    - train category models,
#    - save them to disk.

# 4) Load trained models (if you run on a fresh session):

goodbad_log_model = log_model           # or joblib.load(...) if you saved it
goodbad_rf_model  = rf_model
cat_log_model     = joblib.load(model_cat_logreg_path)
cat_rf_model      = joblib.load(model_cat_rf_path)

# 5) Choose a new folder of images and where to save results:

new_images_dir = NEW_IMAGES_DIR_1
output_excel   = os.path.join(STATS_DIR, "results_new_images_1.xlsx")

# 6) Run the full pipeline:

df_results_new = run_full_pipeline_on_folder(
    images_dir=new_images_dir,
    output_excel_path=output_excel,
    mu=mu,
    sigma=sigma,
    goodbad_log_model=goodbad_log_model,
    goodbad_rf_model=goodbad_rf_model,
    cat_log_model=cat_log_model,
    cat_rf_model=cat_rf_model,
    good_threshold=0.75,
)
"""

# End of script
# ======================================================================